export const COUNTRIES = [
  "Kenya",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Burundi",
  "Ethiopia",
  "Ghana",
  "Nigeria",
  "South Africa",
  "Other",
] as const;

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Kenya: [
    // Nairobi Metro & satellite towns
    "Nairobi",
    "Ruiru",
    "Thika",
    "Kiambu",
    "Kikuyu",
    "Limuru",
    "Githunguri",
    "Gatundu",
    "Ngong",
    "Ongata Rongai",
    "Kitengela",
    "Athi River",
    "Mavoko",
    "Kajiado",
    "Namanga",
    // Coast
    "Mombasa",
    "Nyali",
    "Bamburi",
    "Kilifi",
    "Malindi",
    "Watamu",
    "Diani",
    "Ukunda",
    "Lamu",
    "Voi",
    "Mariakani",
    "Kwale",
    // Rift Valley
    "Nakuru",
    "Naivasha",
    "Gilgil",
    "Molo",
    "Njoro",
    "Eldoret",
    "Turbo",
    "Burnt Forest",
    "Kericho",
    "Litein",
    "Bomet",
    "Sotik",
    "Narok",
    "Nandi Hills",
    "Kapsabet",
    "Kabarnet",
    "Eldama Ravine",
    "Iten",
    "Nanyuki",
    "Rumuruti",
    // Western Kenya
    "Kisumu",
    "Ahero",
    "Maseno",
    "Homa Bay",
    "Kendu Bay",
    "Migori",
    "Awendo",
    "Siaya",
    "Bondo",
    "Kisii",
    "Ogembo",
    "Keroka",
    "Nyamira",
    "Kakamega",
    "Mumias",
    "Butere",
    "Vihiga",
    "Mbale",
    "Bungoma",
    "Webuye",
    "Kimilili",
    "Busia",
    "Malaba",
    "Kitale",
    "Kiminini",
    "Kapenguria",
    // Central Kenya
    "Nyeri",
    "Karatina",
    "Othaya",
    "Murang'a",
    "Kenol",
    "Maragua",
    "Embu",
    "Runyenjes",
    "Chuka",
    "Meru",
    "Nkubu",
    "Timau",
    "Machakos",
    "Kangundo",
    "Kitui",
    // Northern / NFD
    "Garissa",
    "Isiolo",
    "Marsabit",
    "Maralal",
    "Moyale",
    "Wajir",
    "Mandera",
    "Lodwar",
  ],
  Uganda: [
    "Kampala",
    "Entebbe",
    "Jinja",
    "Gulu",
    "Mbarara",
    "Mbale",
    "Arua",
    "Lira",
  ],
  Tanzania: [
    "Dar es Salaam",
    "Dodoma",
    "Arusha",
    "Mwanza",
    "Zanzibar City",
    "Tanga",
    "Morogoro",
    "Mbeya",
  ],
  Rwanda: [
    "Kigali",
    "Huye",
    "Musanze",
    "Rubavu",
    "Nyagatare",
  ],
  Burundi: [
    "Bujumbura",
    "Gitega",
    "Ngozi",
    "Rumonge",
  ],
  Ethiopia: [
    "Addis Ababa",
    "Adama",
    "Bahir Dar",
    "Mekelle",
    "Hawassa",
    "Dire Dawa",
  ],
  Ghana: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Cape Coast",
  ],
  Nigeria: [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Kano",
    "Ibadan",
    "Enugu",
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
  ],
  Other: [],
};

export function getCitiesForCountry(country?: string): string[] {
  if (!country) return [];
  return CITIES_BY_COUNTRY[country] ?? [];
}
