export const COUNTRIES = [
  "Kenya",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Burundi",
  "Ethiopia",
  "Ghana",
  "Nigeria",
  "South Africa",
  "Other",
] as const;

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Thika",
    "Naivasha",
    "Kitale",
    "Malindi",
    "Nyeri",
    "Meru",
    "Embu",
    "Machakos",
    "Kitui",
    "Garissa",
    "Isiolo",
    "Narok",
    "Voi",
    "Kilifi",
    "Lamu",
  ],
  Uganda: [
    "Kampala",
    "Entebbe",
    "Jinja",
    "Gulu",
    "Mbarara",
    "Mbale",
    "Arua",
    "Lira",
  ],
  Tanzania: [
    "Dar es Salaam",
    "Dodoma",
    "Arusha",
    "Mwanza",
    "Zanzibar City",
    "Tanga",
    "Morogoro",
    "Mbeya",
  ],
  Rwanda: [
    "Kigali",
    "Huye",
    "Musanze",
    "Rubavu",
    "Nyagatare",
  ],
  Burundi: [
    "Bujumbura",
    "Gitega",
    "Ngozi",
    "Rumonge",
  ],
  Ethiopia: [
    "Addis Ababa",
    "Adama",
    "Bahir Dar",
    "Mekelle",
    "Hawassa",
    "Dire Dawa",
  ],
  Ghana: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Cape Coast",
  ],
  Nigeria: [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Kano",
    "Ibadan",
    "Enugu",
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
  ],
  Other: [],
};

export function getCitiesForCountry(country?: string): string[] {
  if (!country) return [];
  return CITIES_BY_COUNTRY[country] ?? [];
}
